version: '3.8'

services:
  scylla-1:
    image: scylladb/scylla:5.1
    container_name: scylla-1
    hostname: scylla-1
    ports:
      - "9042:9042"
    command: --reactor-backend=epoll
    networks:
      - scylla-network

  scylla-2:
    image: scylladb/scylla:5.1
    container_name: scylla-2
    hostname: scylla-2
    depends_on:
      - scylla-1
    ports:
      - "9043:9042"
    command: --seeds=scylla-1 --reactor-backend=epoll
    networks:
      - scylla-network

  scylla-3:
    image: scylladb/scylla:5.1
    container_name: scylla-3
    hostname: scylla-3
    depends_on:
      - scylla-1
    ports:
      - "9044:9042"
    command: --seeds=scylla-1 --reactor-backend=epoll
    networks:
      - scylla-network

networks:
  scylla-network:
    driver: bridge
